# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ea0c01bb5a0d924d101d372c56da77ea"
name = "ysabel-mora"
handle = "ysabel-mora"
application_url = "https://jade-awareness-recruiting-remain.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ohd-mcc-development.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_payment_customizations,write_payment_customizations,write_products"

[auth]
redirect_urls = [
  "https://jade-awareness-recruiting-remain.trycloudflare.com/auth/callback",
  "https://jade-awareness-recruiting-remain.trycloudflare.com/auth/shopify/callback",
  "https://jade-awareness-recruiting-remain.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
